# Generated by Django 3.1.4 on 2021-01-11 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='TITLE')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='SLUG')),
                ('addr', models.CharField(max_length=1000, verbose_name='ADDRESS')),
                ('addr_detail', models.CharField(max_length=200, verbose_name='ADDRESS DETAIL')),
                ('description', models.CharField(max_length=200, verbose_name='DESCRIPTION')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
            options={
                'verbose_name': 'forum',
                'verbose_name_plural': 'forums',
                'db_table': 'forum',
                'ordering': ('-modify_dt',),
            },
        ),
    ]
