# Generated by Django 3.1.4 on 2021-01-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias', max_length=100, verbose_name='SLUG'),
        ),
    ]
