# Generated by Django 3.1.4 on 2021-01-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210111_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='addr_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='ADDRESS DETAIL'),
        ),
    ]
