# Generated by Django 3.1.4 on 2021-01-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210111_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='DESCRIPTION'),
        ),
    ]
